version: "3"
services:
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_MAX_ALLOWED_PACKET: 64M
      MYSQL_WAIT_TIMEOUT: 28800
    networks:
      - app-network
  app:
    build:
      context: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
      PASSWORD_MIGRATION: ${PASSWORD_MIGRATION}

networks:
  app-network:
    driver: bridge

volumes:
  db_data: